$folders = @(
  "lib",
  "app/login",
  "app/api/auth/login",
  "app/api/auth/logout",
  "app/api/auth/session",
  "app/api/pacientes/[id]",
  "app/api/personal/[id]",
  "app/api/citas/[id]",
  "app/api/estados-cita",
  "app/api/consultas/[id]",
  "app/api/signos-vitales",
  "app/api/tipos-signo-vital",
  "app/api/diagnosticos",
  "app/api/cie10",
  "app/api/medicamentos/[id]",
  "app/api/formas-farmaceuticas",
  "app/api/lotes-inventario/[id]",
  "app/api/usuarios/[id]",
  "app/api/auditoria",
  "app/api/reportes/excel",
  "app/dashboard/pacientes/[id]",
  "app/dashboard/personal",
  "app/dashboard/citas",
  "app/dashboard/consultas/[id]",
  "app/dashboard/medicamentos",
  "app/dashboard/inventario",
  "app/dashboard/usuarios",
  "app/dashboard/auditoria",
  "components/ui",
  "components/pacientes",
  "components/personal",
  "components/citas",
  "components/consultas",
  "components/inventario",
  "components/medicamentos",
  "scripts"
)

foreach ($f in $folders) {
  New-Item -ItemType Directory -Force -Path $f | Out-Null
}

$files = @(
  "lib/db.js",
  "lib/auth.js",
  "lib/validations.js",
  "lib/utils.js",
  "middleware.js",
  "app/login/page.js",
  "app/api/auth/login/route.js",
  "app/api/auth/logout/route.js",
  "app/api/auth/session/route.js",
  "app/api/pacientes/route.js",
  "app/api/pacientes/[id]/route.js",
  "app/api/personal/route.js",
  "app/api/personal/[id]/route.js",
  "app/api/citas/route.js",
  "app/api/citas/[id]/route.js",
  "app/api/estados-cita/route.js",
  "app/api/consultas/route.js",
  "app/api/consultas/[id]/route.js",
  "app/api/signos-vitales/route.js",
  "app/api/tipos-signo-vital/route.js",
  "app/api/diagnosticos/route.js",
  "app/api/cie10/route.js",
  "app/api/medicamentos/route.js",
  "app/api/medicamentos/[id]/route.js",
  "app/api/formas-farmaceuticas/route.js",
  "app/api/lotes-inventario/route.js",
  "app/api/lotes-inventario/[id]/route.js",
  "app/api/usuarios/route.js",
  "app/api/usuarios/[id]/route.js",
  "app/api/auditoria/route.js",
  "app/api/reportes/excel/route.js",
  "app/dashboard/layout.js",
  "app/dashboard/page.js",
  "app/dashboard/pacientes/page.js",
  "app/dashboard/pacientes/[id]/page.js",
  "app/dashboard/personal/page.js",
  "app/dashboard/citas/page.js",
  "app/dashboard/consultas/page.js",
  "app/dashboard/consultas/[id]/page.js",
  "app/dashboard/medicamentos/page.js",
  "app/dashboard/inventario/page.js",
  "app/dashboard/usuarios/page.js",
  "app/dashboard/auditoria/page.js",
  "components/ui/Sidebar.js",
  "components/ui/Navbar.js",
  "components/ui/Modal.js",
  "components/ui/Table.js",
  "components/ui/LoadingSpinner.js",
  "components/ui/ConfirmDialog.js",
  "components/pacientes/PacienteForm.js",
  "components/personal/PersonalForm.js",
  "components/citas/CitaForm.js",
  "components/citas/CitaCalendario.js",
  "components/consultas/ConsultaForm.js",
  "components/consultas/SignosVitalesForm.js",
  "components/consultas/DiagnosticoForm.js",
  "components/inventario/LoteForm.js",
  "components/inventario/AlertaCaducidad.js",
  "components/medicamentos/MedicamentoForm.js",
  "scripts/schema.sql",
  ".env.local"
)

foreach ($f in $files) {
  if (-not (Test-Path -LiteralPath $f)) {
    New-Item -ItemType File -Force -Path $f | Out-Null
  }
}

Write-Host "Estructura generada correctamente." -ForegroundColor Green
